stages:
  - build
  - test

build-app:
  stage: build
  image: node:alpine
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    untracked: true

test-app:
  stage: test
  image: node:alpine
  script:
    - npm run e2e:headless
  artifacts:
    untracked: true


