stages:
  # - build
  - test

# build-app:
#   stage: build
#   image: node:alpine
#   before_script:
#     - npm install
#   script:
#     - npm run build
#   artifacts:
#     untracked: true

test-app:
  stage: test
  image: cypress/base
  before_script:
    - yarn install
    - yarn build
    - yarn start &
  script:
    - sleep 10
    - yarn cypress:headless
  artifacts:
    untracked: true


