stages:
  - build
  - test

build-app:
  stage: build
  image: node:alpine
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    untracked: true

test-app:
  stage: test
  image: node:alpine
  before_script:
    - npm run cypress:install
    - npm run start &
  script:
    - sleep 20
    - npm run cypress:headless
  artifacts:
    untracked: true


