stages:
  - build
  - test

build-app:
  stage: build
  image: node:alpine
  before_script:
    - npm install
  script:
    - npm run build

test-app:
  stage: test
  image: cypress/base
  before_script:
    - npm install
    - npm run build
    - npm run start &
  script:
    - sleep 10
    - npm run cypress:headless


