stages:
  - build
  - test

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules
    - .next

build-app:
  stage: build
  image: cypress/base
  script:
    - yarn install
    - yarn build
    - npx cypress cache path
    - npx cypress cache list
    - $(npm bin)/print-env CI

test-app:
  stage: test
  image: cypress/base
  script:
    - yarn start &
    - sleep 5
    - yarn cypress:headless
  artifacts:
    untracked: true


